### ISSUE TITLE
Provide a way to design models of a questionnaire

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues#528]
This features should handle several use cases:

- business trends survey ([example](https://www.insee.fr/en/metadonnees/source/serie/s1205?debut=0)) design a questionnaire but its several sub questionnaires that are deployed to answering businesses
- the [consumer confidence survey](https://www.insee.fr/en/metadonnees/source/serie/s1208?debut=0) interogate a rotating household panel over 3 months, using a combination of stable parts and thematic parts of their questionnaire

The underlying DDI model could help defining what is a model or submodel of a questionnaire in those use cases. Once design, we'll have to implement a proper UI or to adapt what is currently existing in Pogues. We'll also need to make sure that Eno can work with the chosen DDI representation.

**EPIC**:

- [ ] Design what is a questionnaire submodel for each use cases
- [ ] Chose the right implementation in DDI
- [ ] Adapt the UI accordingly
- [ ] Check if any evolution of Eno is needed

**Related topics**:

Household surveys use a shared bank of questions and variables (called in French "Le tronc commun des ménages"), maybe we could consider it to be a related use cases of this one ?

**Comment by romaintailhurat** [comment]
Epics are now managed at https://github.com/InseeFr/Umbrella
