### ISSUE TITLE
Manage controls

### ISSUE THREAD

**Issue by ThomasPO** [InseeFr/Pogues#77]
- [ ] Manage contrôls in a specific box [here] (https://github.com/InseeFr/Pogues/issues/97)
- [ ] Enter an error message related to the control [here] (https://github.com/InseeFr/Pogues/issues/98)
- [ ] Define a level of criticality [here] (https://github.com/InseeFr/Pogues/issues/99)

**Comment by ThomasPO** [comment]
Done
