### ISSUE TITLE
Manage variables

### ISSUE THREAD

**Issue by ThomasPO** [InseeFr/Pogues#79]
- [x] Manage collected variables [here](https://github.com/InseeFr/Pogues/issues/94)
- [x] Manage external variables [here](https://github.com/InseeFr/Pogues/issues/95)
- [x] Manage calculated variables [here](https://github.com/InseeFr/Pogues/issues/96)

**Comment by ThomasPO** [comment]
Done.
Issue closed
